{
 "title": "Resource Usage Observatory",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total,namespace)"
    }
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{namespace=\"$namespace\"},workload_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center\">\n  <h2>Resource Usage Observatory</h2>\n</div>"
   }
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (workload_name) (\n        sum by (namespace,pod_name,container_name,name,workload_name) (\n            irate(\n                container_cpu_usage_seconds_total{\n                    namespace=\"$namespace\",\n                    workload_name=~\"$workload\",\n                    container_name!=\"\",\n                    container_name!=\"POD\"\n                }[1m]\n            )\n        )\n    unless\n        sum by (namespace,pod_name,container_name,name,workload_name) (\n                time()\n            -\n                container_last_seen{\n                    namespace=\"$namespace\",\n                    workload_name=~\"$workload\",\n                    container_name!=\"\",\n                    container_name!=\"POD\"\n                }\n            >\n                2\n        )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "# Pod Memory Usage\nsum by (workload_name) (\n        sum by (namespace,pod_name,container_name,name,workload_name) (\n            container_memory_working_set_bytes{\n                namespace=\"$namespace\",\n                workload_name=~\"$workload\",\n                container_name!=\"\",\n                container_name!=\"POD\"\n            }\n        )\n    unless\n        sum by (namespace,pod_name,container_name,name,workload_name) (\n                time()\n            -\n                container_last_seen{\n                    namespace=\"$namespace\",\n                    workload_name=~\"$workload\",\n                    container_name!=\"\",\n                    container_name!=\"POD\"\n                }\n            >\n                2\n        )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "# Pod Memory Max\nsum by (workload_name) (\n        sum by (namespace,pod_name,container_name,name,workload_name) (\n            container_memory_max_usage_bytes{\n                namespace=\"$namespace\",\n                workload_name=~\"$workload\",\n                container_name!=\"\",\n                container_name!=\"POD\"\n            }\n        )\n    unless\n        sum by (namespace,pod_name,container_name,name,workload_name) (\n                time()\n            -\n                container_last_seen{\n                    namespace=\"$namespace\",\n                    workload_name=~\"$workload\",\n                    container_name!=\"\",\n                    container_name!=\"POD\"\n                }\n            >\n                2\n        )\n)",
     "legendFormat": "{{workload_name}} max"
    }
   ]
  }
 ]
}